# Site Settings
title: About Me - Akshay Bhatia
url: 'https://akshayb6.github.io'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Akshay Bhatia
tagline: Computer Science Graduate and Software Developer
pic: Profile2.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Hello, I am a graduate student of Computer Science at Rutgers University and I will be graduating in May 2018. 
I presently serve as a Part-Time Lecuturer at Rutgers and my interests lie in the fields of Machine Learning, Data Mining, Artificial Intelligence and Computational Robotics.
I am actively looking for full-time roles starting in June 2018. You can scroll down to view my Resume or <a href="/resume_akshay_bhatia.pdf" target="_blank">click here to download it</a>. '

#sidebar links
email: thatbhatia@gmail.com
phone: +1(201)606-1877
#website: blog.webjeda.com #do not add http://
linkedin: akshayb6
github: akshayb6
twitter: '@thatbhatia'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-61197187-2

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
